#数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://my.yunout.com:3306/tiger_study?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    # 配置Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
  session:
    store-type: redis
    # 单位秒 默认最短一分钟 默认半小时
    timeout: 300
  redis:
    host: my.yunout.com
    port: 6379
    password: kruiredis0130
    database: 0



# Tomcat
server:
  #port: 8070 qq回调端口要求80  也可以做接口转掉 8060
  port: 80
  connection-timeout: 5000ms
  #servlet:
    #session:
      #timeout: 30


#自定义权限配置
tiger:
  auth:
     browser:
       #loginPage: /demo-login.html # 这里可以配置成自己的非标准登录界面
        loginType: JSON
        signupUrl: /demo-signup.html
        loginOut: /demo-logout.html
     imageCaptcha:
        interceptImageUrl: /user/*,/pay/confirm # 这些路径验证码也要拦截校验
     social:
        filterProcessesUrl: /auth
        #filterProcessesUrl: /qqLogin
        qq:
          app-id: 1013162782602
          app-secret: 34211e019a56566f7d44f4fe58380e69
        wechat:
          app-id: wxd99431bbff8305a0
          app-secret: wxd99431bbff8305a0
          # providerId: qq 默认就是
          # http://www.ictgu.cn/login/qq qq互联申请的回调地址 101386962 2a0f820407df400b84a854d054be8b6a

security:
  oauth2:
    client:
      client-id: tigerauth
      client-secret: 123456
      registered-redirect-uri: http://www.example.com



